name: 定期获取域名IP

on:
  # 设置一个计划任务，例如每天 UTC 时间 02:00 运行
  schedule:
    - cron: '0 2 * * *'
  # 也可以在代码提交到 main 分支时运行
  push:
    branches: [ main ]
  # 允许手动从 Actions 标签页运行
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # 添加写入权限

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Install Playwright browsers
      run: |
        playwright install
        playwright install-deps

    - name: Run Python script
      run: |
        python main.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add hosts_results.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update hosts_results.txt" && git push)
