name: 定期获取域名IP

on:
  schedule:
    - cron: '5 0 * * *'  # 每天 00:05（UTC 时间）执行
  workflow_dispatch:      # 支持手动运行
  push:
    branches: [ main ]

jobs:
  run-script:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Playwright browsers
      run: |
        playwright install
        playwright install-deps

    - name: Run Python script
      run: |
        python main.py

    - name: Commit and push if changed
      run: |
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "github-actions[bot]"
        git add hosts_results.txt
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update hosts_results.txt" && git push)
