name: 定期获取域名IP

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 0 点执行

jobs:
  lookup-ips:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v4

      - name: 安装 dig 工具
        run: sudo apt-get update && sudo apt-get install -y dnsutils

      - name: 查询 IP 并生成 hosts 文件
        run: |
          INPUT_FILE="domains.txt"
          OUTPUT_FILE="hosts_results.txt"

          echo "# GitHub 相关域名最新 IP 地址 (Hosts 格式)" > $OUTPUT_FILE
          echo "# 最后更新于: $(date -u)" >> $OUTPUT_FILE
          echo "" >> $OUTPUT_FILE

          while IFS= read -r domain || [[ -n "$domain" ]]; do
            [[ -z "$domain" || "$domain" =~ ^# ]] && continue
            echo "查询中: $domain"

            ips=$(dig +short A "$domain" | sort -u | tr '\n' ' ' | sed 's/ *$//')

            if [[ -n "$ips" ]]; then
              for ip in $ips; do
                echo "$ip $domain" >> $OUTPUT_FILE
              done
              echo "" >> $OUTPUT_FILE
            else
              echo "# 未能解析 IP: $domain" >> $OUTPUT_FILE
              echo "" >> $OUTPUT_FILE
            fi
          done < "$INPUT_FILE"

      - name: 提交并推送结果
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions-bot@users.noreply.github.com'
          git add hosts_results.txt

          if ! git diff --cached --quiet; then
            git commit -m "自动更新域名IP地址列表"
            git push
          else
            echo "无变化，无需提交"
          fi
